# Generated by Django 4.2.4 on 2023-08-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='contato',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
