# Generated by Django 4.2.2 on 2023-08-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0004_alter_category_options_contato_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='picture',
            field=models.ImageField(upload_to='pictures/%Y/%m/'),
        ),
    ]
